# Generated by Django 5.0 on 2024-01-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_hardstore_record_storehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='email',
            field=models.CharField(default='@mail', max_length=100),
            preserve_default=False,
        ),
    ]
