# Generated by Django 5.0 on 2024-01-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_record_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='position',
        ),
        migrations.AddField(
            model_name='record',
            name='date_of_birth',
            field=models.CharField(default='01.01.2000', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='date_pockypki',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='record',
            name='male_choice',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(default='@mail', max_length=200),
        ),
    ]
